### PR TITLE
with args

### PR DESCRIPTION
**Pull request by bluelovers**

### CODE REVIEW

**Comment by bluelovers** [comment]
@olstenlarck when allow use acorn and babylon, i thought they have same node.params

i see u use yarn, so i think u can use resolutions for make sure acorn only has one version

**Comment by bluelovers** [comment]
i also update parseFnParams for support babylon for this test function

https://github.com/bluelovers/node-func-args/commit/f24e66f6f2f25f98d1a87a5ab2bac2a459f3b849#diff-ed009b6b86b017532ef0489c77de5100

```ts
let fn = async (a, b, c, {e, d, }, [aa1, aa2, { aaa3 }, [ bbb1, bbb2, { bbb4 } ], ...rrr], e2 = null, f = {
		g: 7,
		a: 8,
		b: {
			c: 555,
			d: true,
		},
	},
	f2 = (333), ...argv) => {};
```

```ts
[ 'a',
  'b',
  'c',
  'e',
  'd',
  'aa1',
  'aa2',
  'aaa3',
  'bbb1',
  'bbb2',
  'bbb4',
  '...rrr',
  'e2',
  'f',
  'f2',
  '...argv' ]
```

**Comment by luiscarbonell** [comment]
Implemented the pull request locally and it breaks the `defaults` hidden value.

**Comment by tunnckoCore** [comment]
Sorry for the delay, I missed that I think. It's quite old too. Check #203, closing.

**Pull request closed without merging**
